# Generated by Django 5.2.9 on 2025-12-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionProteccion',
            fields=[
                ('id_accion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Acción de Protección',
                'verbose_name_plural': 'Acciones de Protección',
                'db_table': 'AccionProteccion',
            },
        ),
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id_amenaza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Amenaza',
                'verbose_name_plural': 'Amenazas',
                'db_table': 'Amenaza',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comun', models.CharField(max_length=200)),
                ('nombre_cientifico', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('distribucion', models.TextField(blank=True, null=True)),
                ('importancia_ecologica', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Preocupación menor (LC)', 'Preocupación menor (LC)'), ('Casi amenazado (NT)', 'Casi amenazado (NT)'), ('Vulnerable (VU)', 'Vulnerable (VU)'), ('En peligro (EN)', 'En peligro (EN)'), ('Peligro crítico (CR)', 'Peligro crítico (CR)')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'db_table': 'Animal',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('Aves', 'Aves'), ('Mamíferos', 'Mamíferos'), ('Reptiles', 'Reptiles'), ('Peces marinos', 'Peces marinos'), ('Equinodermos', 'Equinodermos'), ('Anfibios', 'Anfibios')], max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='AnimalAccionProteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.ForeignKey(db_column='id_accion', on_delete=django.db.models.deletion.CASCADE, to='fauna.accionproteccion')),
                ('animal', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.CASCADE, to='fauna.animal')),
            ],
            options={
                'verbose_name': 'Animal-Acción de Protección',
                'verbose_name_plural': 'Animal-Acciones de Protección',
                'db_table': 'AnimalAccionProteccion',
                'unique_together': {('animal', 'accion')},
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='acciones_proteccion',
            field=models.ManyToManyField(related_name='animales', through='fauna.AnimalAccionProteccion', to='fauna.accionproteccion'),
        ),
        migrations.CreateModel(
            name='AnimalAmenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenaza', models.ForeignKey(db_column='id_amenaza', on_delete=django.db.models.deletion.CASCADE, to='fauna.amenaza')),
                ('animal', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.CASCADE, to='fauna.animal')),
            ],
            options={
                'verbose_name': 'Animal-Amenaza',
                'verbose_name_plural': 'Animal-Amenazas',
                'db_table': 'AnimalAmenaza',
                'unique_together': {('animal', 'amenaza')},
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='amenazas',
            field=models.ManyToManyField(related_name='animales', through='fauna.AnimalAmenaza', to='fauna.amenaza'),
        ),
        migrations.AddField(
            model_name='animal',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='fauna.categoria'),
        ),
        migrations.CreateModel(
            name='FotoAnimal',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('url_foto', models.CharField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('animal', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='fauna.animal')),
            ],
            options={
                'verbose_name': 'Foto de Animal',
                'verbose_name_plural': 'Fotos de Animales',
                'db_table': 'FotoAnimal',
            },
        ),
    ]
