# Generated by Django 5.2.9 on 2025-12-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('id_planta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comun', models.CharField(max_length=200)),
                ('nombre_cientifico', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('distribucion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Preocupación menor (LC)', 'Preocupación menor (LC)'), ('Vulnerable (VU)', 'Vulnerable (VU)'), ('En peligro (EN)', 'En peligro (EN)'), ('Peligro crítico (CR)', 'Peligro crítico (CR)')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Flora',
                'verbose_name_plural': 'Flora',
                'db_table': 'Flora',
            },
        ),
        migrations.CreateModel(
            name='FotoFlora',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('url_foto', models.CharField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('planta', models.ForeignKey(db_column='id_planta', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='flora.flora')),
            ],
            options={
                'verbose_name': 'Foto de Flora',
                'verbose_name_plural': 'Fotos de Flora',
                'db_table': 'FotoFlora',
            },
        ),
    ]
