# Generated by Django 5.2.9 on 2025-12-04 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=200)),
                ('nombre_cientifico', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('distribucion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('LC', 'Preocupación menor (LC)'), ('VU', 'Vulnerable (VU)'), ('EN', 'En peligro (EN)'), ('CR', 'Peligro crítico (CR)')], default='LC', max_length=50)),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'db_table': 'Flora',
                'ordering': ['nombre_comun'],
                'indexes': [models.Index(fields=['nombre_comun'], name='Flora_nombre__04f94f_idx'), models.Index(fields=['nombre_cientifico'], name='Flora_nombre__a83eb8_idx'), models.Index(fields=['estado'], name='Flora_estado_c5da47_idx')],
            },
        ),
        migrations.CreateModel(
            name='FotoFlora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_foto', models.URLField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('planta', models.ForeignKey(db_column='id_planta', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='flora.flora')),
            ],
            options={
                'verbose_name': 'Foto de Planta',
                'verbose_name_plural': 'Fotos de Plantas',
                'db_table': 'FotoFlora',
            },
        ),
    ]
